# 服务启动端口
server:
  port: 8080

# 华为云配置信息
huawei:
  # App Key
  app_key: "apigateway_sdk_demo_key"
  # App Secret
  app_secret: "apigateway_sdk_demo_secret"
  # APP接入地址(在控制台"应用管理"页面获取)+接口访问URI
  api_address: "https://smsapi.cn-south-1.myhuaweicloud.com:443/sms/batchSendSms/v1"
  # 国内短信签名通道号
  sender: "******"
  # 模板ID
  template_id: "******"

  # 条件必填,国内短信关注,当templateId指定的模板类型为通用模板时生效且必填,必须是已审核通过的,与模板类型一致的签名名称
  # 签名名称
  signature: "**信息"
  # 选填,短信状态报告接收地址,推荐使用域名,为空或者不填表示不接收状态报告
  status_call_back: ""

# 告警方式
alerts:
  # 华为云 sms 告警
  - type: huawei-msgsms
    enabled: on
  # 内蒙古医科大学附属医院-短信平台
  - type: nmgykdxfsyy-sms
    enabled: off

# 接收方
receivers:
  - name: 用户1
    # 电话 未添加国家码 +86 ,程序会自动添加 +86
    contact_numbers:
#      - 12345678901
#      - +8601234567890
  - name: 用户2
    contact_numbers:
#      - "+8611122220000"
#      - 22233334444